spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 22

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


#logging:
#  level:
#    com.zaxxer.hikari.HikariConfig: TRACE
#    com.zaxxer.hikari: TRACE